### PR TITLE
Update 001_ATONE_DISTRIBUTION.md

### PR DESCRIPTION
**Pull request by WaqarMMirza**
I was doing my calculations and in a quick recap table, There should be "+" in the NWV column if I am not mistaken.

### CODE REVIEW

**Comment by tbruyelle** [comment]
Well, that depends on how you define the bonus. Considering we want a 3% bonus, if bonus=1.03, the current format works well, and this is how we applied it in the code.

**Comment by WaqarMMirza** [comment]
I believe the code will work fine. But for the text part, either it should be "9 + bonus" or 9 x (1+bonus).  Noway that "9 x bonus" represents the whole factor 1.03 it represents "9 x 0.03 = 0.27" 

But again, it was worth mentioning so I did. I can live with that.

**Comment by giunatale** [comment]
I would agree with @tbruyelle here, I think changing the proposal logic wrt to the code would make things ambiguous. Maybe we can specify that in the table, bonus and malus are not the raw percentages but they include the +1, so bonus is 1.03 and malus 0.97. If you want @WaqarMMirza you can propose the change yourself here in this PR.

I would add the clarification below the table, like

> where `bonus` and `malus` are respectively `1.03` and `0.97` as per the above specifications.

Or something like that.

I would not change the table though.

**Comment by tbruyelle** [comment]
@WaqarMMirza we added a new NOTE in the proposal to address the confusion you have raised.

**Comment by giunatale** [comment]
https://github.com/atomone-hub/govgen-proposals/pull/13

**Comment by giunatale** [comment]
I will be closing this, since we hope we addressed it. Please @WaqarMMirza don't hesitate to re-open, ask more questions or clarifications, and thanks for proofreading!

**Comment by WaqarMMirza** [comment]
@giunatale @tbruyelle thank you both for addressing the issue.

**Pull request closed without merging**
